---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-share-controller
  namespace: gitlab

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-share-controller
subjects:
  - kind: ServiceAccount
    name: node-share-controller
    namespace: gitlab
roleRef:
  kind: ClusterRole
  name: "system:node"
  apiGroup: rbac.authorization.k8s.io
