---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: builds-spack-io
  namespace: spack
spec:
  tls:
  - secretName: tls-spackbuilds
  rules:
  - host: builds.spack.io
    http:
      paths:
      - backend:
          serviceName: builds-spack-io
          servicePort: 80         
      - path: /static
        backend:
          serviceName: static-service
          servicePort: 80
      - path: /images
        backend:
          serviceName: images-services
          servicePort: 80
