---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: gitlab

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: gitlab
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "secrets"]
  verbs: ["get", "watch", "list", "update", "create", "patch", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runner
  namespace: gitlab
subjects:
- kind: ServiceAccount
  name: runner
roleRef:
  kind: Role
  name: runner
  apiGroup: rbac.authorization.k8s.io
