---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spack-io
    svc: web
  name: spack-io
  namespace: spack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spack-io
      svc: web
  template:
    metadata:
      labels:
        app: spack-io
        svc: web
    spec:
      containers:
      - image: ghcr.io/spack/spack.io:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        spack.io/node-pool: base
