---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spack-packages
    svc: web
  name: spack-packages
  namespace: spack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spack-packages
      svc: web
  template:
    metadata:
      labels:
        app: spack-packages
        svc: web
    spec:
      containers:
      - image: spack/packages.spack.io:latest
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        spack.io/node-pool: base
