---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spack-io
    svc: web-redirect
  name: spack-io-redirect
  namespace: spack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spack-io
      svc: web-redirect
  template:
    metadata:
      labels:
        app: spack-io
        svc: web-redirect
    spec:
      containers:
      - env:
        - name: SERVER_REDIRECT
          value: spack.io
        image: schmunk42/nginx-redirect
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        spack.io/node-pool: base
