---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slack-spack-io
    svc: web
  name: slack-spack-io
  namespace: spack
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: slack-spack-io
    svc: web
  type: ClusterIP
