---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-cdash
  namespace: cdash
spec:
  commonName: cdash.spack.io
  dnsNames:
  - cdash.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-cdash
