---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  dnsNames:
  - minio.gitlab.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-gitlab-minio
