---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-slack
  namespace: spack
spec:
  commonName: slack.spack.io
  dnsNames:
  - slack.spack.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-slack
