---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spack-packages
  namespace: spack
spec:
  rules:
  - host: packages.spack.io
    http:
      paths:
      - backend:
          serviceName: spack-packages
          servicePort: 80
  tls:
  - secretName: tls-packages
