---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  chart:
    name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 11.16.0
  releaseName: prometheus
  values:
    alertmanager:
      baseURL: https://alertmanager.spack.io
      enabled: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: 'true'
        enabled: true
        hosts:
        - alertmanager.spack.io
        tls:
        - hosts:
          - alertmanager.spack.io
          secretName: prometheus-alerts-tls
      nodeSelector:
        spack.io/node-pool: base
      replicaCount: 3
      statefulSet:
        enabled: true
    nodeExporter:
      nodeSelector:
        spack.io/node-pool: base
    pushgateway:
      enabled: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: 'true'
        enabled: true
        hosts:
        - pushgateway.spack.io
        tls:
        - hosts:
          - pushgateway.spack.io
          secretName: prometheus-alerts-tls
      nodeSelector:
        spack.io/node-pool: base
      replicaCount: 3
    server:
      baseURL: prometheus.spack.io
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: 'true'
        enabled: true
        hosts:
        - prometheus.spack.io
        tls:
        - hosts:
          - prometheus.spack.io
          secretName: prometheus-server-tls
      nodeSelector:
        spack.io/node-pool: base
      replicaCount: 3
      statefulSet:
        enabled: true
      verticalAutoscaler:
        enabled: false
