---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cdash-updater
  namespace: cdash
rules:
- apiGroups:
  - ''
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  - pods
  - pods/exec
  verbs:
  - get
  - watch
  - list
  - update
  - create
  - patch
  - delete
