---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-www
spec:
  secretName: tls-www
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: logs.spack.io
  dnsNames:
  - logs.spack.io
