---
apiVersion: v1
kind: Secret
metadata:
  name: logs-spack-io-secrets
  namespace: logs-spack-io
  annotations:
      fluxcd.io/ignore: "true"
data:
  # These are all fake secrets!
  matomo_database_tables_prefix: hakunamatata
  mysql_root_password: hakunamatata
  mysql_host: hakunamatata
  mysql_user: hakunamatata
  mysql_password: hakunamatata
  mysql_database: hakunamatata
