---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-unicorn-temp
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-unicorn-temp
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-registry-temp
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-registry-temp
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - registry.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-minio-temp
  namespace: gitlab
  annotations:
    fluxcd.io/ignore: "true"
spec:
  secretName: tls-gitlab-minio-temp
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - minio.next.spack.io
