---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-unicorn
  namespace: gitlab
spec:
  secretName: tls-gitlab-unicorn
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - gitlab.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  secretName: tls-gitlab-registry
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - registry.next.spack.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  secretName: tls-gitlab-minio
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - minio.next.spack.io
